#! /usr/bin/env python3
import os
import requests

src_dir = "data/feedback/"
#import requests
files = os.listdir(src_dir)
dir="/data/feedback/"
url= "http://Source URL/feedback/"


#Process a directory of text files 
def readlines(file):
    with open(src_dir + file) as f:
        lines = f.read().splitlines()
    return lines


#Manage information
feedback = []
keys = ["title", "name", "date", "feedback"]
for file in files:
    lines = readlines(file)
    feedback.append(dict(zip(keys, lines)))


#Upload content
for entry in feedback:
    response = requests.post(url, data=entry)
    if response.ok:
        print("loaded entry")
    else:
        print(f"load entry error: {response.status_code}")
